spring:
  profiles:
    active: dev
---
spring:
  r2dbc:
    url: r2dbc:postgresql://localhost:5432/postgres
    username: postgres
    password: password
  config:
    activate:
      on-profile: dev
logging:
  level:
    org.springframework.data.r2dbc: Debug
server:
  port: 8081
---
spring:
  r2dbc:
    url: r2dbc:h2:mem:///test?options=DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
    name: sa
    password:
  config:
    activate:
      on-profile: test
---
spring:
  r2dbc:
    url: r2dbc:postgresql://localhost:5432/test
    username: postgres
    password: Pass2020!
  logging:
    level:
      org.springframework: Debug
  config:
    activate:
      on-profile: prod

